//export const server = "https://greenchaindb.web.app"
export const server = "http://127.0.0.1:8080"
export const get_reports_path = "/get-reports"
export const report_path = "/create-report"
export const register_path = "/register"
export const get_user_id_path = "/get-user-id"
export const get_username_path = "/get-username"